import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Shield, Truck, CreditCard } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { useCart } from '@/contexts/CartContext';
import { useDeliveryCharges, useMetaPixel } from '@/hooks/useSettings';
import { formatPrice } from '@/utils/formatters';
import { trackInitiateCheckout, trackPurchase } from '@/utils/metaPixel';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { z } from 'zod';

const checkoutSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  phone: z.string().min(10, 'Please enter a valid phone number').max(20),
  address: z.string().min(10, 'Please enter your full address').max(500),
  email: z.string().email('Invalid email').optional().or(z.literal('')),
  notes: z.string().max(500).optional(),
});

type CheckoutForm = z.infer<typeof checkoutSchema>;

export default function CheckoutPage() {
  const navigate = useNavigate();
  const { items, getSubtotal, clearCart } = useCart();
  const deliveryCharges = useDeliveryCharges();
  const metaPixel = useMetaPixel();

  const [form, setForm] = useState<CheckoutForm>({
    name: '',
    phone: '',
    address: '',
    email: '',
    notes: '',
  });
  const [errors, setErrors] = useState<Partial<Record<keyof CheckoutForm, string>>>({});
  const [deliveryLocation, setDeliveryLocation] = useState<'inside' | 'outside'>('inside');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const subtotal = getSubtotal();
  const deliveryCharge = subtotal >= deliveryCharges.free_shipping_threshold 
    ? 0 
    : deliveryLocation === 'inside' 
      ? deliveryCharges.inside_city 
      : deliveryCharges.outside_city;
  const total = subtotal + deliveryCharge;

  // Track InitiateCheckout
  useEffect(() => {
    if (items.length > 0 && metaPixel.enabled) {
      trackInitiateCheckout({
        value: subtotal,
        numItems: items.reduce((sum, item) => sum + item.quantity, 0),
        contentIds: items.map(item => item.product.id),
      });
    }
  }, []);

  // Redirect if cart is empty
  useEffect(() => {
    if (items.length === 0) {
      navigate('/cart');
    }
  }, [items.length, navigate]);

  const handleInputChange = (field: keyof CheckoutForm, value: string) => {
    setForm(prev => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: undefined }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      // Validate form
      const validatedData = checkoutSchema.parse(form);

      // Create customer
      const { data: customer, error: customerError } = await supabase
        .from('customers')
        .insert({
          name: validatedData.name,
          phone: validatedData.phone,
          email: validatedData.email || null,
          address: validatedData.address,
        })
        .select()
        .single();

      if (customerError) throw customerError;

      // Create order - order_number is auto-generated by database trigger
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          order_number: `ACS-${Date.now()}`, // Placeholder, trigger will override
          customer_id: customer.id,
          customer_name: validatedData.name,
          customer_phone: validatedData.phone,
          customer_email: validatedData.email || null,
          customer_address: validatedData.address,
          notes: validatedData.notes || null,
          subtotal,
          delivery_charge: deliveryCharge,
          total,
          payment_method: 'COD',
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map(item => ({
        order_id: order.id,
        product_id: item.product.id,
        title_snapshot: item.product.title,
        price_snapshot: item.product.price,
        image_snapshot: item.product.product_images?.find(img => img.is_primary)?.url 
          || item.product.product_images?.[0]?.url || null,
        qty: item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Track Purchase event
      if (metaPixel.enabled) {
        trackPurchase({
          orderId: order.order_number,
          value: total,
          contentIds: items.map(item => item.product.id),
        });
      }

      // Clear cart and redirect
      clearCart();
      navigate(`/order-confirmation/${order.order_number}`);

    } catch (error) {
      if (error instanceof z.ZodError) {
        const fieldErrors: Partial<Record<keyof CheckoutForm, string>> = {};
        error.errors.forEach(err => {
          const field = err.path[0] as keyof CheckoutForm;
          fieldErrors[field] = err.message;
        });
        setErrors(fieldErrors);
      } else {
        console.error('Checkout error:', error);
        toast.error('Failed to place order. Please try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  if (items.length === 0) {
    return null;
  }

  return (
    <div className="min-h-screen bg-secondary/30">
      <div className="container-custom py-8">
        <Link to="/cart" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary mb-6">
          <ArrowLeft className="h-4 w-4 mr-2" /> Back to Cart
        </Link>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Checkout Form */}
          <div>
            <div className="bg-card rounded-xl shadow-card p-6">
              <h1 className="text-2xl font-serif font-bold mb-6">Checkout</h1>

              <form onSubmit={handleSubmit} className="space-y-5">
                {/* Name */}
                <div>
                  <Label htmlFor="name">Full Name *</Label>
                  <Input
                    id="name"
                    value={form.name}
                    onChange={(e) => handleInputChange('name', e.target.value)}
                    placeholder="Enter your full name"
                    className={errors.name ? 'border-destructive' : ''}
                  />
                  {errors.name && <p className="text-sm text-destructive mt-1">{errors.name}</p>}
                </div>

                {/* Phone */}
                <div>
                  <Label htmlFor="phone">Phone Number *</Label>
                  <Input
                    id="phone"
                    type="tel"
                    value={form.phone}
                    onChange={(e) => handleInputChange('phone', e.target.value)}
                    placeholder="01XXXXXXXXX"
                    className={errors.phone ? 'border-destructive' : ''}
                  />
                  {errors.phone && <p className="text-sm text-destructive mt-1">{errors.phone}</p>}
                </div>

                {/* Email (Optional) */}
                <div>
                  <Label htmlFor="email">Email (Optional)</Label>
                  <Input
                    id="email"
                    type="email"
                    value={form.email}
                    onChange={(e) => handleInputChange('email', e.target.value)}
                    placeholder="your@email.com"
                    className={errors.email ? 'border-destructive' : ''}
                  />
                  {errors.email && <p className="text-sm text-destructive mt-1">{errors.email}</p>}
                </div>

                {/* Address */}
                <div>
                  <Label htmlFor="address">Delivery Address *</Label>
                  <Textarea
                    id="address"
                    value={form.address}
                    onChange={(e) => handleInputChange('address', e.target.value)}
                    placeholder="Enter your complete address including house/flat number, area, city"
                    rows={3}
                    className={errors.address ? 'border-destructive' : ''}
                  />
                  {errors.address && <p className="text-sm text-destructive mt-1">{errors.address}</p>}
                </div>

                {/* Delivery Location */}
                <div>
                  <Label className="mb-3 block">Delivery Location</Label>
                  <RadioGroup value={deliveryLocation} onValueChange={(v: 'inside' | 'outside') => setDeliveryLocation(v)}>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="inside" id="inside" />
                      <Label htmlFor="inside" className="font-normal cursor-pointer">
                        Inside Dhaka ({formatPrice(deliveryCharges.inside_city)})
                      </Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="outside" id="outside" />
                      <Label htmlFor="outside" className="font-normal cursor-pointer">
                        Outside Dhaka ({formatPrice(deliveryCharges.outside_city)})
                      </Label>
                    </div>
                  </RadioGroup>
                  {subtotal >= deliveryCharges.free_shipping_threshold && (
                    <p className="text-sm text-success mt-2">🎉 You qualify for free shipping!</p>
                  )}
                </div>

                {/* Notes */}
                <div>
                  <Label htmlFor="notes">Order Notes (Optional)</Label>
                  <Textarea
                    id="notes"
                    value={form.notes}
                    onChange={(e) => handleInputChange('notes', e.target.value)}
                    placeholder="Any special instructions for your order"
                    rows={2}
                  />
                </div>

                {/* Payment Method */}
                <div className="p-4 bg-secondary rounded-lg">
                  <div className="flex items-center gap-3">
                    <CreditCard className="h-5 w-5 text-primary" />
                    <div>
                      <p className="font-medium">Cash on Delivery (COD)</p>
                      <p className="text-sm text-muted-foreground">Pay when you receive your order</p>
                    </div>
                  </div>
                </div>

                <Button
                  type="submit"
                  size="lg"
                  className="w-full btn-hero"
                  disabled={isSubmitting}
                >
                  {isSubmitting ? 'Placing Order...' : `Place Order - ${formatPrice(total)}`}
                </Button>
              </form>
            </div>
          </div>

          {/* Order Summary */}
          <div>
            <div className="bg-card rounded-xl shadow-card p-6 sticky top-24">
              <h2 className="text-xl font-serif font-bold mb-4">Order Summary</h2>

              {/* Items */}
              <div className="space-y-4 border-b border-border pb-4 mb-4">
                {items.map(item => {
                  const image = item.product.product_images?.find(img => img.is_primary)?.url
                    || item.product.product_images?.[0]?.url
                    || '/placeholder.svg';
                  return (
                    <div key={item.product.id} className="flex gap-3">
                      <img
                        src={image}
                        alt={item.product.title}
                        className="w-16 h-16 object-cover rounded-lg"
                      />
                      <div className="flex-1 min-w-0">
                        <p className="font-medium text-sm line-clamp-2">{item.product.title}</p>
                        <p className="text-sm text-muted-foreground">Qty: {item.quantity}</p>
                      </div>
                      <span className="font-medium text-sm">
                        {formatPrice(item.product.price * item.quantity)}
                      </span>
                    </div>
                  );
                })}
              </div>

              {/* Totals */}
              <div className="space-y-2 border-b border-border pb-4 mb-4">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>{formatPrice(subtotal)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Delivery</span>
                  <span>{deliveryCharge === 0 ? 'FREE' : formatPrice(deliveryCharge)}</span>
                </div>
              </div>

              <div className="flex justify-between font-bold text-lg">
                <span>Total</span>
                <span className="text-primary">{formatPrice(total)}</span>
              </div>

              {/* Trust Badges */}
              <div className="mt-6 space-y-2">
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Shield className="h-4 w-4 text-primary" />
                  <span>Secure Checkout</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Truck className="h-4 w-4 text-primary" />
                  <span>Fast & Reliable Delivery</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
